use_frameworks!

target 'EggLoadingView_Example' do
  pod 'EggLoadingView', :path => '../'
   pod 'EggDeviceExt'
   pod 'SwiftyGif'

  target 'EggLoadingView_Tests' do
    inherit! :search_paths

    
  end
end
